on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: postgres-CDMConnector

jobs:
  postgres-CDMConnector:
    runs-on: ubuntu-latest

    env:
      CDM5_POSTGRESQL_SERVER: ${{ secrets.CDM5_POSTGRESQL_SERVER }}
      CDM5_POSTGRESQL_USER: ${{ secrets.CDM5_POSTGRESQL_USER }}
      CDM5_POSTGRESQL_PASSWORD: ${{ secrets.CDM5_POSTGRESQL_PASSWORD }}

    strategy:
      fail-fast: true
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools
          needs: check

      - name: Run tests on postgres
        run: |
          Sys.setenv("DB_TO_TEST" = "postgres CDMConnector")
          x <- devtools::test()
          error <- sum(as.numeric(dplyr::as_tibble(x)$error))
          failed <- sum(as.numeric(dplyr::as_tibble(x)$failed))
          if (error + failed > 0) cli::cli_abort(c(x = "Tests failed"))
        shell: Rscript {0}
