on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: test-postgres-CDMConnector

jobs:
  test-postgres-CDMConnector:
    runs-on: ubuntu-latest

    name: test-postgres-CDMConnector

    strategy:
      fail-fast: true
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools
          needs: check

      - name: Run tests on postgres
        run: |
          Sys.setenv("DB_TO_TEST" = "postgres CDMConnector")
          x <- devtools::test()
          print(x)
          failed <- sum(dplyr::as_tibble(x)$failed)
          if (failed > 0) cli::cli_abort(c(x = "{failed} tests failed!"))
        shell: Rscript {0}
