on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

name: snowflake-CDMConnector

jobs:
  snowflake-CDMConnector:
    runs-on: ubuntu-latest

    env:
      CDM_SNOWFLAKE_USER: ${{ secrets.CDM_SNOWFLAKE_USER }}
      CDM_SNOWFLAKE_PASSWORD: ${{ secrets.CDM_SNOWFLAKE_PASSWORD }}
      CDM_SNOWFLAKE_CONNECTION_STRING: ${{ secrets.CDM_SNOWFLAKE_CONNECTION_STRING }}

    strategy:
      fail-fast: true
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools
          needs: check

      - name: Install unixODBC and Snowflake ODBC
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev ca-certificates wget
          wget https://sfc-repo.snowflakecomputing.com/odbc/linux/ubuntu20/snowflake-odbc_2.25.6_amd64.deb -O snowflake-odbc.deb
          sudo dpkg -i snowflake-odbc.deb
          odbcinst -q -d

      - name: Run tests on snowflake
        run: |
          Sys.setenv("DB_TO_TEST" = "snowflake CDMConnector")
          x <- devtools::test()
          error <- sum(as.numeric(dplyr::as_tibble(x)$error))
          failed <- sum(as.numeric(dplyr::as_tibble(x)$failed))
          if (error + failed > 0) cli::cli_abort(c(x = "Tests failed"))
        shell: Rscript {0}
